trigger:
  - main

variables:
  buildConfiguration: 'Release'
  vmImageName: 'vs2017-win2016'
  functionAppName: 'famyhealthexceptions'
  azureSubscription: 'e86d34ea-25ef-4288-8ffb-5baaea87a61b'
  workingDirectory: '$(System.DefaultWorkingDirectory)/MyHealth.Exceptions'
  projectName: 'MyHealth.Exceptions'

stages:
  - stage: Build
    displayName: Build Stage

    jobs:
      - job: Build
        displayName: Build $(projectName)
        pool:
          vmImage: $(vmImageName)
        
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
    
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: --configuration $(buildConfiguration)
    
          - task: DotNetCoreCLI@2
            displayName: Run Unit Tests
            inputs:
              command: 'test'
              projects: '**/*UnitTests/*.csproj'
    
          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '**/*.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
              zipAfterPublish: True
            
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'
  
  - stage: Deploy
    displayName: 'Deploy $(projectName)'
    dependsOn: Build
    condition: succeeded()

    jobs:
      - deployment: Deploy
        displayName: Deploy $(projectName)
        environment: Production
        pool:
          vmImage: $(vmImageName)

        strategy:
          runOnce:
            deploy:
              
              steps:
                - task: AzureRmWebAppDeployment@4
                  displayName: 'Deploy Azure Function'
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appType: functionApp
                    WebAppName: $(functionAppName)                   
                    package: '$(Pipeline.Workspace)/drop/MyHealth.Exceptions.zip'
                    appSettings: '-FUNCTIONS_WORKER_RUNTIME "dotnet" -FUNCTIONS_EXTENSION_VERSION "~3" -FunctionOptions:ExceptionRecipientEmail "willvelida@hotmail.co.uk" -FunctionOptions:ExceptionRecipientName "Will Velida" -FunctionOptions:SendGridAPIKey "@Microsoft.KeyVault(SecretUri=https://willvelidakeyvault.vault.azure.net/secrets/sendgridapikey/d5d54864df0e415db8d7168d2cc8b3e6)" -FunctionOptions:ServiceBusConnectionString "@Microsoft.KeyVault(SecretUri=https://willvelidakeyvault.vault.azure.net/secrets/servicebusstorageconnectionstring/65723514479d44d5a3846dce260b98bb)" -APPINSIGHTS_INSTRUMENTATIONKEY "2fc597df-fc6b-4b20-ac9c-ee7240b70704"'
                    enableCustomDeployment: true
                    RemoveAdditionalFilesFlag: true